/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Cestari
 */
public class form2 extends javax.swing.JFrame {

    /**
     * Creates new form form2
     */
    public form2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(600, 250, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setText("Salir");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Adivina el país");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 255, 153));
        jButton3.setText("Verificar");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 153));
        jButton4.setText("Jugar");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/f.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    int k,vidas, banderarnd, juego;
    String jugador,paisElegido;
    Random rnd = new Random();
    String [] banderas = new String[7];
   
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(Color.DARK_GRAY);           
        jugador = JOptionPane.showInputDialog("Ingrese su nombre");
        JOptionPane.showMessageDialog(null, "Presionar el boton jugar para comenzar ");
        jButton3.setEnabled(false);
        if (jugador.equalsIgnoreCase("") || jugador.isEmpty()) {
            jLabel3.setText("Jugador");
       }else{
            jLabel3.setText(jugador);
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
                //boton jugar
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      JOptionPane.showMessageDialog(null,"Introduce el nombre del país y presione verificar");     
      jLabel4.setIcon(new ImageIcon(getClass().getResource("/img/corazon.png")));
      jLabel16.setIcon(new ImageIcon(getClass().getResource("/img/corazon.png")));
      jLabel17.setIcon(new ImageIcon(getClass().getResource("/img/corazon.png")));
      jLabel17.setEnabled(true);
      jLabel16.setEnabled(true);
      jLabel4.setEnabled(true);
      jTextField1.setText("");
      jButton4.setEnabled(false);
      jButton3.setEnabled(true);
     
        banderas[0]="argentina";     
        banderas[1]="colombia";
        banderas[2]="islandia";
        banderas[3]="noruega";
        banderas[4]="dinamarca";
        banderas[5]="turquia";
        banderas[6]="alemania";       
        
        banderarnd = rnd.nextInt(banderas.length);
        System.out.println("Indice del array:"+banderarnd);
        
        paisElegido = banderas[banderarnd];
        System.out.println("Bandera elegida:"+paisElegido);
        
        if (paisElegido.equalsIgnoreCase("argentina") ) {           
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/argentina.png")));
            juego = 1;
        }else if (paisElegido.equalsIgnoreCase("colombia")) {
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/colombia.png")));
            juego = 2;
        }else if (paisElegido.equalsIgnoreCase("alemania")) {
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/alemania.png")));
            juego = 3;
        }else if (paisElegido.equalsIgnoreCase("islandia")) {
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/islandia.png")));
            juego = 4;
        }else if (paisElegido.equalsIgnoreCase("noruega")) {
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/noruega.png")));
            juego = 5;
        }else if (paisElegido.equalsIgnoreCase("turquia")) {
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/turquia.png")));
            juego = 6;
        }else if (paisElegido.equalsIgnoreCase("dinamarca")) {
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/dinamarca.png")));
            juego = 7;
        }
        vidas = 0;
        
         
    }//GEN-LAST:event_jButton4ActionPerformed
            
                    //boton verificar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        switch (juego) {
            case 1:
                if (jTextField1.getText().equalsIgnoreCase("argentina")) {
                    JOptionPane.showMessageDialog(null,"Usted ha ganado!");
                    jButton4.setEnabled(true);
                    jButton3.setEnabled(false);
                }else{
                    vidas++;
                }              
                break;               
                case 2:                   
                if (jTextField1.getText().equalsIgnoreCase("colombia")) {
                    JOptionPane.showMessageDialog(null,"Usted ha ganado!");
                    jButton4.setEnabled(true);
                    jButton3.setEnabled(false);
                }else{
                    vidas++;
                }               
                break;
                case 3:
                if (jTextField1.getText().equalsIgnoreCase("alemania")) {
                    JOptionPane.showMessageDialog(null,"Usted ha ganado!");
                    jButton4.setEnabled(true);
                   jButton3.setEnabled(false);
                }else{
                    vidas++;
                }               
                break;
                case 4:
                if (jTextField1.getText().equalsIgnoreCase("islandia")) {
                    JOptionPane.showMessageDialog(null,"Usted ha ganado!");
                    jButton4.setEnabled(true);
                    jButton3.setEnabled(false);
                }else{
                    vidas++;
                }               
                break;
                case 5:
                if (jTextField1.getText().equalsIgnoreCase("noruega")) {
                    JOptionPane.showMessageDialog(null,"Usted ha ganado!");
                    jButton4.setEnabled(true);
                   jButton3.setEnabled(false);
                }else{
                    vidas++;
                }               
                break;
                case 6:
                if (jTextField1.getText().equalsIgnoreCase("turquia")) {
                    JOptionPane.showMessageDialog(null,"Usted ha ganado!");
                    jButton4.setEnabled(true);
                    jButton3.setEnabled(false);
                }else{
                    vidas++;
                }               
                break;
                case 7:
                if (jTextField1.getText().equalsIgnoreCase("dinamarca")) {
                    JOptionPane.showMessageDialog(null,"Usted ha ganado!");
                    jButton4.setEnabled(true);
                   jButton3.setEnabled(false);
                }else{
                    vidas++;
                }               
                break;                          
        }
        
        
        switch (vidas) {
            case 1:
                jLabel17.setEnabled(false);
                break;
                case 2:
                jLabel16.setEnabled(false);
                break;
                case 3:
                jLabel4.setEnabled(false);
                break;          
        }
        
        if (vidas >= 3){
            JOptionPane.showMessageDialog(null, "Usted ha perdido");
            jButton3.setEnabled(false);
            jButton4.setEnabled(true);
        }
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
